version: "3.8"

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

services: 
  havend:
    container_name: havend
    build:
      context: dockerfiles
      dockerfile: haven_nocompile
      network: host
    restart: unless-stopped
    volumes:
      - ${HAVEN_DIR:-./data}:/data
    ports:
      - ${HAVEN_P2P_PORT:-17750}:17750                    # p2p
      - ${HAVEN_RESTRICTED_PORT:-17751}:17751             # restricted rpc
      - 127.0.0.1:${HAVEN_ZMQ_PORT:-17752}:17752          # zmq
      - 127.0.0.1:${HAVEN_UNRESTRICTED_PORT:-17753}:17753 # unrestricted rpc
      - 127.0.0.1:${HAVEN_ZMQ_PUB_PORT:-17754}:17754      # ZMQ PUB Port
    command:
      #havend  --no-zmq --prune-blockchain --sync-pruned-blocks --add-priority-node=xhv.gntl.uk:17750  --add-priority-node=node.haven.tools:17750 --add-priority-node=nodes.hashvault.pro:17750  --add-priority-node=remote.eu.havenprotocol.org:17750 --zmq-pub tcp://0.0.0.0:17754 --zmq-rpc-bind-ip=0.0.0.0 --zmq-rpc-bind-port=17752 --data-dir=/data --p2p-bind-ip=0.0.0.0 --p2p-bind-port=17750 --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=17751 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=17753 --confirm-external-bind --log-level=0 --non-interactive --rpc-ssl=disabled --out-peers 64 --in-peers 32
      #havend --zmq-pub tcp://0.0.0.0:17754 --add-priority-node=node.haven.tools:17750 --add-priority-node=nodes.hashvault.pro:17750  --add-priority-node=remote.eu.havenprotocol.org:17750 --p2p-use-ipv6 --data-dir=/data --p2p-bind-ip=0.0.0.0 --p2p-bind-port=17750 --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=17751 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=17753 --non-interactive --confirm-external-bind --public-node --log-level=0 --enable-dns-blocklist --disable-dns-checkpoints --rpc-ssl=disabled --out-peers 64 --in-peers 32
    <<: *log-config