version: "3.8"

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

services: 
  zephyrd:
    container_name: zephyrd
    build:
      context: dockerfiles
      dockerfile: zephyr_compile
      network: host
    volumes:
      - ${ZEPHYR_DIR:-./data}:/data
    ports:
      - ${ZEPHYR_P2P_PORT:-19080}:19080                    # p2p
      - ${ZEPHYR_RESTRICTED_PORT:-19081}:19081             # restricted rpc
      - 127.0.0.1:${ZEPHYR_ZMQ_PORT:-19082}:19082          # zmq
      - 127.0.0.1:${ZEPHYR_UNRESTRICTED_PORT:-19083}:19083 # unrestricted rpc
      - 127.0.0.1:${ZEPHYR_ZMQ_PUB_PORT:-19084}:19084      # ZMQ PUB Port
    command:
      zephyrd --data-dir=/data --p2p-bind-ip=0.0.0.0 --p2p-bind-port=19080 --restricted-rpc --rpc-restricted-bind-ip=0.0.0.0 --rpc-restricted-bind-port=19081 --zmq-rpc-bind-ip=0.0.0.0 --zmq-rpc-bind-port=19082 --rpc-bind-ip=0.0.0.0 --rpc-bind-port=19083 --non-interactive --confirm-external-bind --public-node --log-level=0 --enable-dns-blocklist --rpc-ssl=disabled --zmq-pub tcp://0.0.0.0:19084 #--prune-blockchain --sync-pruned-blocks
    <<: *log-config