version: "3.7"

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

services: 
  p2pool:
    image: sethsimmons/p2pool:latest
    restart: unless-stopped
    container_name: p2pool
    tty: true
    stdin_open: true
    volumes:
      - ${P2POOL_DIR:-./p2pool}:/home/p2pool
      - /dev/hugepages:/dev/hugepages:rw
    ports:
      - 3333:3333
      - 37888:37888
    command: --mini --wallet "${WALL}" --stratum "0.0.0.0:3333" --p2p "0.0.0.0:37888" --loglevel "4" --host "monerod" --rpc-port 18081 --zmq-port 18083 --host monerod --addpeers node.portemonero.com:37888 --start-mining 1
    <<: *log-config
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_POLL_INTERVAL: 3600
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    <<: *log-config