version: "3.8"

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

services: 
  litecoin-core:
    container_name: litecoin-core
    image: ghcr.io/sethforprivacy/litecoind:latest
    command:
      - -printtoconsole
      - -rpcallowip=0.0.0.0/0  # Allow RPC from ElectrumX
      - -rpcbind=0.0.0.0
      - -rpcuser=litecoinrpc
      - -rpcpassword=dBMgDFvtN5QbcmjkBREZua4R8  # Change this!
      - -server=1
      - -txindex=1  # Required for ElectrumX full transaction indexing
      - -blockfilterindex=1  # Optional, enhances client queries
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/litecoind-data/_data:/litecoin/.litecoin  # Persistent blockchain data
    ports:
      - "9332:9332"  # RPC port
      - "9333:9333"  # P2P port
    restart: unless-stopped
    <<: *log-config

  electrumx:
    container_name: electrumx
    build:
      context: dockerfiles
      dockerfile: mweb_electrum_ltc
      network: host
    environment:
      - DAEMON_URL=http://litecoinrpc:dBMgDFvtN5QbcmjkBREZua4R8@litecoin-core:9332  # Match RPC credentials
      - COIN=Litecoin
      - NET=mainnet
      - SERVICES=tcp://0.0.0.0:50001  #,ssl://0.0.0.0:50002  # Electrum client ports
      - PEER_DISCOVERY=on
      - ALLOW_ROOT=true  # For Docker simplicity
      - DB_DIRECTORY=/electrumx/db  # Persistent DB storage
      - ELECTRUMX_REQUEST_TIMEOUT=30
    volumes:
      - electrumx-data:/electrumx/db  # Persistent ElectrumX data
    ports:
      - "50001:50001"  # TCP for Electrum clients
      - "50002:50002"  # SSL for Electrum clients
    depends_on:
      - litecoin-core
    <<: *log-config


volumes:
    electrumx-data: